### ISSUE TITLE
connect metask fail

### ISSUE THREAD

**Issue by cmcvip** [Particle-Network/particle-connect-android#4]
Sometimes when calling connect and jumping to metamask, the connection option cannot be called, and it will be suspended on the metamask page

**Comment by cmcvip** [comment]
有时候调用connect方法连接metamask 跳转过去后 无反应 假死在metamask app中 不会弹起连接选项

**Comment by duanlian89** [comment]
> 有时候调用connect方法连接metamask 跳转过去后 无反应 假死在metamask app中 不会弹起连接选项

你好，请问这个问题得到解决了吗？我也遇到了同样的问题，想请教一下是如何解决的。
